# Generated by Django 4.2.6 on 2023-11-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardset',
            name='number_of_flashcards',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='study_level',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
