# Generated by Django 4.2.6 on 2023-11-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_flashcardset_number_of_flashcards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardset',
            name='topic',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
