# Generated by Django 4.2.6 on 2023-11-27 03:12

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_flashcardset_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardset',
            name='id',
            field=models.CharField(default=app.models.generate_unique_id, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
